feat: provide SideroLink client implementation
talos-systems/talos pull request #4565
Opened 2021-11-19 20:06 UTC by smira

Related to #4448

The only remaining part is filtering out SideroLink addresses when Talos
looks for a node address.

See also https://github.com/talos-systems/siderolink/pull/2

The way to test it out:

```
$ talosctl cluster create ... --extra-boot-kernel-args
siderolink.api=172.20.0.1:4000
```

(where 172.20.0.1 is the bridge IP)

Run `siderolink-agent` (test implementation):

```
$ sudo _out/siderolink-agent-linux-amd64
```

Now on the host, there should be a `siderolink` Wireguard userspace
tunnel:

```
$ sudo wg
interface: siderolink
  public key: 2aq/V91QyrHAoH24RK0bldukgo2rWk+wqE5Eg6TArCM=
  private key: (hidden)
  listening port: 51821

peer: Tyr6C/F3FFLWtnzqq7Dsm54B40bOPq6++PTiD/zqn2Y=
  endpoint: 172.20.0.1:47857
  allowed ips: fdae:41e4:649b:9303:b6db:d99c:215e:dfc4/128
  latest handshake: 2 minutes, 2 seconds ago
  transfer: 3.62 KiB received, 1012 B sent

...
```

Each Talos node will be registered as a peer, tunnel is established.

You can now ping Talos nodes from the host over the tunnel:

```
$ ping fdae:41e4:649b:9303:b6db:d99c:215e:dfc4
PING fdae:41e4:649b:9303:b6db:d99c:215e:dfc4(fdae:41e4:649b:9303:b6db:d99c:215e:dfc4) 56 data bytes
64 bytes from fdae:41e4:649b:9303:b6db:d99c:215e:dfc4: icmp_seq=1 ttl=64 time=0.352 ms
64 bytes from fdae:41e4:649b:9303:b6db:d99c:215e:dfc4: icmp_seq=2 ttl=64 time=0.437 ms
```

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

2021-11-19 20:07 UTC, smira commented
/approve

2021-11-20 09:23 UTC, frezbo requested changes
small typo

2021-11-20 09:23 UTC, frezbo commented on cmd/talosctl/cmd/mgmt/cluster/create.go
> +	createCmd.Flags().StringVar(&extraBootKernelArgs, "extra-boot-kernel-args", "", "add extra kernel args to the initial boot from vmlinuz and initramgs (QEMU only)")
```suggestion
	createCmd.Flags().StringVar(&extraBootKernelArgs, "extra-boot-kernel-args", "", "add extra kernel args to the initial boot from vmlinuz and initramfs (QEMU only)")
```

2021-11-20 09:23 UTC, frezbo commented on website/content/docs/v0.14/Reference/cli.md
> +      --extra-boot-kernel-args string           add extra kernel args to the initial boot from vmlinuz and initramgs (QEMU only)
```suggestion
--extra-boot-kernel-args string           add extra kernel args to the initial boot from vmlinuz and initramfs (QEMU only)
```

2021-11-22 13:22 UTC, Unix4ever approved these changes

2021-11-22 13:22 UTC, Unix4ever commented on internal/app/machined/pkg/controllers/siderolink/manager.go
> +	Cmdline *procfs.Cmdline
minor nit: probably it should use the same letter case as we already have in  `TimeServerConfigController`: `Cmdline`.

2021-11-22 14:55 UTC, frezbo approved these changes

2021-11-22 15:05 UTC, smira commented
/m --ff

2021-11-22 15:05 UTC, merged